# Point this feeder at the reconfiguration server - this is where the load/unload
# services can be found. It follws the usual ros namespacing conventions - i.e.
# it can be an absolute global name (e.g. /reconfiguration) or it can be
# representative of a sibling namespace as is the case here
server_namespace: reconfiguration

# Define your individual dyn-recfg servers here
parameters:

  # A dyn-recfg server definition - with this name it will be found at 'reconfiguration/dude'
  dude:
    # The dyn-recfg type (it is actually a python module) - don't forget the 'Config' suffix!
    module: feed_the_troll.cfg.DemoConfig
    # Load some initialisations to the param server that override those in the .cfg files
    overrides:
      int_param: 5
      double_param: 0.6
      str_param: Dude
      bool_param: False
      size: 2

  # Another dyn-recfg server definition - will be found at 'reconfiguration/dudette'
  dudette:
    module: feed_the_troll.cfg.DemoConfig
    overrides:
      int_param: 5
      double_param: 0.6
      str_param: Dudette
      bool_param: False
      size: 2
